### ISSUE TITLE
DV partitioning seems inconsistent

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/mdentropy#27]
It seems to yield accurate but imprecise entropy estimates. Not sure how to improve this.... could be the choice of alpha or perhaps chi-squared is an inadequate test (e.g. use Fisher's exact or binomial tests instead)

**Comment by cxhernandez** [comment]
chi-squared helped, but it's still finicky

**Comment by cxhernandez** [comment]
@dr-nate brought this to my attention from the original `mutinf` paper:

>Adaptive partitions make efficient use of discrete bins, preserve correlations between variables, and normalize each joint distribution to a reference distribution in which marginal counts are as uniform as discretization allows. In this work, we used 24 bins per dimension. Adaptive partitions also enable accurate mutual information values to be calculated whether torsional motions are large or small.

This seems to suggest that there's a set number of bins that they use for adaptive binning? It's hard to tell for sure if this is what is actually implemented (code is fairly obfuscated), but it's worth a try.

**Comment by dr-nate** [comment]
The McClendon paper references [this paper](http://bioinformatics.oxfordjournals.org/content/18/suppl_2/S231.abstract) when it covers adaptive binning, and the "Adaptive Partitioning" section in that paper says this:

> We shall now discuss one aspect of the mutual information, which has been neglected so far. As also accounted for by Michaels et al. (1998), the mutual information depends on the distribution of the individual datasets: I (X, Y ) is bounded by the individual entropies of X and Y .
> 
> I (X, Y ) ≤ min{H(X), H(Y )}
> 
> Since our perspective is to do a comparison of the mutual information between datasets, we have to ascertain that the results are not blurred by the individual distributions of measured gene-expression values. The most straightforward strategy is to normalize all measured datasets to an identical reference distribution. Since correlations are preserved under such a transformation, this does not affect the validity of our analysis. Suppose the dataset X has an arbitrary distribution p(x) which is generated by the rule x = h(ξ ) with ξ having the desired well defined simple probability distribution (e.g. uniform or Gaussian) and _h_ being a static monotonic function. The primary task is now to approximate the inverse function.
> 
> ξ = h^{-1} (x)
> 
> This is usually done by rank ordering the elements of {ξ } to the same rank ordering as the elements of {x} (Rapp et al., 1994; Schreiber and Schmitz, 2000). Two sets have the same rank ordering if the j th element is the kth largest in both sets. In practical applications we rank-order the data to a uniform distribution with zero mean. Alternatively, one might use a equivalent method, which mimics the above described transformation. Instead of using fixed intervals to divide the axes into discrete bins, an adaptive partitioning method is applied. That is, each axis is partitioned into M discrete bins, each bin containing (approximately) k = N/M datapoints Consequently, the width of each interval is determined by the local density of the measured dataset.


If I'm not misunderstanding this, it sounds like you just choose some distribution as your baseline and then map all other distributions onto that one. E.g. if you were doing rotational degrees, you could say your baseline is a 0º–360º range, then map any distribution by it's min/max onto that range (?). Or more simply, as it suggests, if all degrees have the same cardinality, you can just use the same number of bins but evenly stretched over the smaller or larger domain of that DOF. That's much less fancy than I would have assumed from a term like "adaptive", but perhaps it works well? And you've already got that implemented, basically.

That _Bioinformatics_ paper goes on to discuss another more sophisticated method, but then says it's not meaningfully better:

> _The Fraser–Swinney algorithm._ ... this algorithm, though mathematically ingenious, does not lead to a substantial improvement in the estimation of mutual information compared to a simple adaptive partitioning approach.

Again, if I'm not misunderstanding this, this whole thing is much simpler than we're imagining.

**Comment by cxhernandez** [comment]
![](http://gif.co/y2ly.gif)

**Comment by cxhernandez** [comment]
abandoning this for now
