### ISSUE TITLE
Create iPython NB of sample use cases

### ISSUE THREAD

**Issue by evanfeinberg** [msmbuilder/mdentropy#43]
Hi CXH, 

This is a very nifty package you've put together here. I'd like to help make it as seamless as possible for other MDTraj/MSMBuilder/MD-with-Python users to integrate this into their pipeline. Ultimately, I'd like to make an iPython notebook that can go in an ```examples``` directory or something of the like in this package.

It seems that much of the user-exposed code (e.g., scripts) are predicated on having PDB files or full trajectories. However, I couldn't figure out easily from the source code how to take my pre-featurized trajectories (essentially, a list of ~2000 NumPy arrays each with ~4500 columns) and calculate the transfer entropy between two features (i.e. random variables) that are two columns in this list of arrays. Or, for example, to compute the TEnt between all pairs of columns. Would you mind helping me do this? I'll make a nice iPython notebook of the result and submit with a PR.

Again, thank you so much for contributing this package, now let's get it distributed!

Evan

**Comment by cxhernandez** [comment]
Waiting to publish stuff before I put up full documentation, but, yes, this is sorely needed.

**Comment by evanfeinberg** [comment]
Gotcha. What do you recommend as a short term solution? Given that a bunch of features are custom (e.g., Ligand-Protein contacts), is there a way to calculate transfer entropy just from NumPy arrays?

**Comment by cxhernandez** [comment]
```python
from mdentropy.core import ncmutinf

transfer_entropy = ncmutinf(n_bin, x_present, y_past, x_past, method='grassberger')
```

**Comment by evanfeinberg** [comment]
Great, thank you! 

Couple questions, apologies in advance if they are elementary as I am still very new to this area:

In the equation for transfer entropy (e.g., https://en.wikipedia.org/wiki/Transfer_entropy), it looks one only needs one time-series containing data for each of two random variables ```x``` and ```y```. In this case, why does one need a separate ```x_present``` in addition to simply ```y_past``` and ```x_past``` in the equation above? Put another way, in the source here, why is a ```z``` needed in addition to ```x``` and ```y```:

```
def ncmutinf(n_bins, x, y, z, rng=None, method='knn'):
    """Normalized conditional mutual information calculation
    Parameters
    ----------
    n_bins : int
        Number of bins.
    x : array_like, shape = (n_samples, n_dim)
        Conditioned variable
    y : array_like, shape = (n_samples, n_dim)
        Conditioned variable
    z : array_like, shape = (n_samples, n_dim)
        Conditional variable
    rng : list
        List of min/max values to bin data over.
    method : {'kde', 'chaowangjost', 'grassberger', 'knn', None}
        Method used to calculate entropy.
    Returns
    -------
    ncmi : float
    """

    return (cmutinf(n_bins, x, y, z, rng=rng, method=method) /
            centropy(n_bins, x, z, rng=rng, method=method))
```

Separate question: any recommendation on how to calculate a single value for the transfer entropy between to variables for many trajectories/arrays/time-series?

**Comment by cxhernandez** [comment]
done this in #46
