### ISSUE TITLE
MDentropy conda install error: Package not found

### ISSUE THREAD

**Issue by MamtaMohan** [msmbuilder/mdentropy#55]
Hi,

I am trying to install mdentropy following instructions from:
http://msmbuilder.org/mdentropy/development/installation.html

I am getting following error. 

Fetching package metadata .................
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
- mdentropy

You can search for packages on anaconda.org with

```
anaconda search -t conda mdentropy
```

I also tried to call it via MSMBuilder and I am getting following error:
In [1]: from msmbuilder.example_datasets import FsPeptide
## In [2]: from mdentropy.metrics import DihedralMutualInformation

ImportError                               Traceback (most recent call last)
<ipython-input-2-b69bad9e7189> in <module>()
----> 1 from mdentropy.metrics import DihedralMutualInformation

ImportError: No module named mdentropy.metrics

I will appreciate your response.

Mamta

**Comment by cxhernandez** [comment]
This package is still in development, and not currently available via `conda`.  I'd recommend using:

```bash
pip install git+git://github.com/pandegroup/mdentropy.git
```
for easy installation of the latest version.

**Comment by MamtaMohan** [comment]
Thank you. I will.


Are some of the metrics functional for analysis?


________________________________

**Comment by cxhernandez** [comment]
> Are some of the metrics functional for analysis?

Yes
