### ISSUE TITLE
direct information

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/mdentropy#57]
implement this

**Comment by cxhernandez** [comment]
Just to clarify, is this the same as [directed information](https://en.wikipedia.org/wiki/Directed_Information)? In which case, we should discuss with @ihwang.

**Comment by brookehus** [comment]
Don't think so. What I'm talking about was introduced [here](http://www.pnas.org/content/108/49/E1293.abstract) as an alternative to mutual information

**Comment by cxhernandez** [comment]
Ah, I see. Not sure about its relevance to MD data though. Wanna discuss this offline?

**Comment by brookehus** [comment]
For sure

**Comment by cxhernandez** [comment]
@brookehus is this still something you want to do?

**Comment by brookehus** [comment]
you can close it, can't see myeslf having time in the near future
