### ISSUE TITLE
Question: Entropy calculation for conformation

### ISSUE THREAD

**Issue by MamtaMohan** [msmbuilder/mdentropy#59]
Hi,

I want to calculate entropy for conformations after building MSM.

I was reading example and I see the example first identifies pathways and then calculate mutual information.

 I am not looking for pathways but I want to calculate entropy in dihedral angle space for each conformation which is recognized by MSM see their relation.

Is pathway calculation necessary. Is it possible without pathway calculation.

I would appreciate your response.

**Comment by cxhernandez** [comment]
> Is pathway calculation necessary. 
No.

> Is it possible without pathway calculation.
Yes.
