### ISSUE TITLE
Selecting residues when using mdentropy.metrics.AlphaAngleMutualInformation

### ISSUE THREAD

**Issue by ragarwa4** [msmbuilder/mdentropy#64]
My protein has two domains and I just want to perform MI of one domain WRT other domain. How can I add this mask?

**Comment by cxhernandez** [comment]
You can use [`Trajectory.atom_slice`](http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.atom_slice) to select atoms that you would like to use in the analysis.
