### ISSUE TITLE
[ JOSS Review ]

### ISSUE THREAD

**Issue by anotherjoshsmith** [msmbuilder/mdentropy#65]
I've played with MDEntropy over the last couple days and haven't run into any problems with the core functionality. The only box left [unchecked](https://github.com/openjournals/joss-reviews/issues/427) is due to an installation issue with a fresh Python 2.7.14 environment. Looks like MDEntropy asks for Python 3.5* on the py27 channel. 

- [ ] Fix Python 2.7 install 

As soon as this is checked, I'll suggest JOSS accept your submission!

A couple of other suggestions, just to help out potential first time users:
- [x] link to [MDEntropy Website]( http://msmbuilder.org/mdentropy) from the GitHub README. I only found the website after looking reading the paper.
- [x] note specific dependencies for the Mutual Information example [here](http://msmbuilder.org/mdentropy/0.3.0/examples/index.html). Should just be matplotlib, nglview, and msmexplorer.

Looks like another useful tool for MD analysis, nice work!

**Comment by cxhernandez** [comment]
> The only box left unchecked is due to an installation issue with a fresh Python 2.7.14 environment. Looks like MDEntropy asks for Python 3.5* on the py27 channel.

I actually need to update the documentation! The package only supports python 3.4+ currently, due to some design choices.

The other points, I do right now! Thanks!

**Comment by anotherjoshsmith** [comment]
Thanks @cxhernandez. With those updates, I think MDEntropy is ready for acceptance by JOSS.
