### ISSUE TITLE
Calculate High Dimension Mutual Information Using mdentropy.mutinf

### ISSUE THREAD

**Issue by Martin1937** [msmbuilder/mdentropy#71]
Hi, I find that the library of mdentropy.mutinf only requires inputs to have same samples, the dimension of x and y could be different. Does it mean that this library could be used for high dimension mutual information calculation ?  For example, if I want to calculate the mutual information between a 5 X 2 data set and a 5 X 3 data set, then I feed those two datasets into mutinf library. If the single value returned is the mutual information ? Btw, what should be the proper value for n_bins ?

thanks in advance !

**Comment by cxhernandez** [comment]
> Hi, I find that the library of mdentropy.mutinf only requires inputs to have same samples, the dimension of x and y could be different. Does it mean that this library could be used for high dimension mutual information calculation ?

Yup!

> Btw, what should be the proper value for n_bins ?

By default, `mutinf` uses a k-nearest neighbors estimator. I've found that `n_bins=3` usually does a good job of maintaining accuracy and reasonable runtimes.
