### ISSUE TITLE
Mutual Information drops if we included more variables using mutinf

### ISSUE THREAD

**Issue by Martin1937** [msmbuilder/mdentropy#72]
Hi, I am recently using mutinf to calculate the high order mutual information. This function is amazingly well. But I found a question that the mutual information of I(A,B,C;Y) could be larger than I (A,B,C,D;Y), which means the mutual information could drop if we include additional variables.  
But according to chain rule below, including additional variable will not decrease the mutual information.

I did a simple experiment and my code is below:
data_48 = mutinf(10,x_48_feature,label_new,rng=None, method='knn')
data_49 = mutinf(10,x_49_feature,label_new,rng=None, method='knn')

x_48_feature is a 1176 * 48 dimension dataset ,   x_49_feature is a 1176 * 49 dimension data and label_new is a 1176 * 1 dimension dataset. The first 48 columns of x_49_features are exactly same as x_48_feature. I add an additional column to x_48_feature to create the x_49_feature. The experiment results show that data_48 (0.32)  is greater than data_49 (0.31) which conflicts the chain rule of mutual information below.  May I know why it is like this ?  Thanks a lot  :)

![1516166122636](https://user-images.githubusercontent.com/35216219/35027467-dfb5dc40-fb8b-11e7-8082-53d560c9422f.jpg)

**Comment by cxhernandez** [comment]
This is strange behavior. I'll preface this by saying that it's entirely likely that there's an issue with my implementation, but at the moment I'm unsure what it could be in that regard.

My gut feeling is that this is a combination of things related to low sampling (i.e. you only have 1E3 data points) and entropy estimation with high-dimensionalities. The k-NN estimator is finicky, particularly in low data, high noise regimes. You could try another estimator (e.g. Grassberger) and see if that helps, but I think that generally having many tens of dimensions complicates this calculation.

My other thought is that the estimator, as implemented, is meant to calculate mutual information between continuous variables. So the data you've given it makes the calculation ill-posed. I have not yet attempted to implement a version of the calculation that is compatible between different variable types.

**Comment by Martin1937** [comment]
It works with Grassberger. Thanks for your help !

**Comment by cxhernandez** [comment]
Great to hear!
