### ISSUE TITLE
Implement Adaptive Partitioning

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/mdentropy#8]
Adaptive Partitioning using the Darbellay-Vajda Algorithm (http://biomedical-engineering-online.biomedcentral.com/articles/10.1186/1475-925X-11-19#Sec7)

**Comment by cxhernandez** [comment]
This method seems to do pretty poorly with uniformly sampled data. Would be great if someone could review [this code](https://github.com/cxhernandez/mdentropy/blob/adaptive/mdentropy/utils.py#L34) and make sure I'm not doing something completely wrong.

(cc @msultan)

**Comment by msultan** [comment]
Based upon a fast reading of the paragraph above eq 10  from 
http://biomedical-engineering-online.biomedcentral.com/articles/10.1186/1475-925X-11-19#Sec7
Isn't the behavior with the uniform distribution expected? 

I am not familiar with the method, but i can read the paper and check out the code today.

**Comment by cxhernandez** [comment]
> Isn't the behavior with the uniform distribution expected?

Maybe. But I would've expected some big **bold-faced warning** about how you shouldn't use this for uniformly distributed data.


> I am not familiar with the method, but i can read the paper and check out the code today.

Thanks! Here's the [original paper](http://bsp.teithe.gr/members/downloads/mutin/references/00761290.pdf) for this algorithm too. Let's talk about it IRL.

**Comment by msultan** [comment]
lol, i think the trick is the 95% CI test where the assumption is that the data is uniformly partitioned in the cubes and when it is not, the cubes are subdivided until they are. 
The uniform distribution with the highest analytical entropy is probably the worst case scenario for this mdl.

**Comment by cxhernandez** [comment]
Okay, following our IRL discussion, I'll add a `min_partitions` flag to avoid the uniform problem; however, an entropy of zero for a uniform distribution isn't actually an issue for mutual information or transfer entropy calculations in theory.

**Comment by cxhernandez** [comment]
also cc @mpharrigan: @msultan and I were thinking this partitioning method might be interesting for MSM construction and adaptive sampling since it creates clusters with uniformly distributed conformations. Low-density states are probably regions where more sampling is necessary.

**Comment by cxhernandez** [comment]
done in #20
